GET http://localhost:8080/Usuario/

###

POST http://localhost:8080/Usuario/
Content-Type: application/json

{
  "Nombre": "Rasasasaaart",
  "Correo": "robert@masterbeer.com",
  "Contraseña": "elkks"
}

###
GET http://localhost:8080/Usuario/5e9f5ed238d348db9572d0d4

###