//Usuarios
export const CREATE_USUARIO = "CREATE_USER";
export const LOAD_USUARIOS_SUCCESS = "LOAD_USUARIOS_SUCCESS";
export const GET_USER_BY_CORREO="GET_USER_BY_CORREO";

//Botellas
export const LOAD_BOTELLAS_SUCCESS = "LOAD_BOTELLAS_SUCCESS";
export const CREATE_BOTELLA = "CREATE_BOTELLA";
export const AGREGAR_BOTELLA = "AGREGAR_BOTELLA";
//Bebidas

//Ingredientes
export const LOAD_INGREDIENTES_SUCCESS = "LOAD_INGREDIENTES_SUCCESS";
export const CREATE_INGREDIENTE = "CREATE_INGREDIENTE";