//Usuarios
export const CREATE_USUARIO = "CREATE_USER";
export const LOAD_USUARIOS_SUCCESS = "LOAD_USUARIOS_SUCCESS";
export const GET_USER_BY_CORREO="GET_USER_BY_CORREO";

//Botellas
export const LOAD_BOTELLAS_SUCCESS = "LOAD_BOTELLAS_SUCCESS";
export const CREATE_BOTELLA = "CREATE_BOTELLA";
export const AGREGAR_BOTELLA = "AGREGAR_BOTELLA";
export const ELIMINAR_BOTELLA = "ELIMINAR_BOTELLA";
export const CARGAR_BOTELLA = "CARGAR_BOTELLA";
//Bebidas

//Pedidos
export const LOAD_PEDIDOS_SUCCESS = "LOAD_PEDIDOS_SUCCESS";
export const HACER_PEDIDO = "HACER_PEDIDO";
export const ELIMINAR_PEDIDO = "ELIMINAR_PEDIDO";

//Ingredientes
export const LOAD_INGREDIENTE_SUCCESS = "LOAD_INGREDIENTE_SUCCESS";
export const CREATE_INGREDIENTE = "CREATE_INGREDIENTE";
export const ELIMINAR_INGREDIENTE = "ELIMINAR_INGREDIENTE";

//Carrito
export const AGREGAR_AL_CARRITO = "AGREGAR_AL_CARRITO";
export const ELIMINAR_DEL_CARRITO = "ELIMINAR_DEL_CARRITO";
export const LOAD_CARRITO = "LOAD_CARRITO";
export const VACIAR_CARRITO = "VACIAR_CARRITO";

//Creador
export const AGREGAR_RECIPIENTE = "AGREGAR_RECIPIENTE";

//Recipientes
export const LOAD_RECIPIENTE_SUCCESS = "LOAD_RECIPIENTE_SUCCESS";
export const CREATE_RECIPIENTE = "CREATE_RECIPIENTE";
export const ELIMINAR_RECIPIENTE = "ELIMINAR_RECIPIENTE";

//Session
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const ACTUAL_USER = "ACTUAL_USER";
